# Model Configuration
model:
  static_dim: 15
  dynamic_dim: 8
  medication_dim: 12
  d_model: 256
  n_heads: 8
  n_layers: 6
  d_ff: 512
  dropout: 0.1
  max_seq_len: 10

# Training Configuration
training:
  batch_size: 64
  learning_rate: 0.0001
  epochs: 100
  patience: 10
  weight_decay: 0.01

# Data Configuration
data:
  seq_length: 10
  prediction_horizons: [3, 5, 10]
  hypotension_threshold: 65.0
  train_split: 0.8
  val_split: 0.2

# Feature Configuration
features:
  static:
    - 'age'
    - 'bmi'
    - 'sex'
    - 'asa_grade'
    - 'emergency_indicator'
    - 'high_blood_type'
    - 'high_diabetes_type'
  
  dynamic:
    - 'map'
    - 'heart_rate'
    - 'respiratory_rate'
    - 'spo2'
    - 'etco2'
    - 'psbp'
    - 'pdbp'
  
  medication:
    - 'propofol'
    - 'opioid_ci'
    - 'opioid_bolus'
    - 'sedatives'
    - 'vasopressor_ci'
    - 'vasopressor_bolus'
